name: my_cat
description: This app for cat

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # icons
  cupertino_icons: ^1.0.2

  # json parsing
  json_annotation: ^4.8.1
  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # linter
  flutter_lints: ^2.0.0

  # dart generator
  build_runner: ^2.4.5

  # json parsing
  json_serializable: ^6.7.0
  freezed: ^2.3.5

  # unit testing
  test: ^1.24.1
  mockito: ^5.4.2

flutter:

  uses-material-design: true

  assets:
    - assets/audios/
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/lotties/
    - assets/test/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
