name: my_cat
description: This app for cat

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # icons
  cupertino_icons: ^1.0.2

  # json parsing
  json_annotation: ^4.8.1
  freezed_annotation: ^2.2.0

  # either - functional programming
  fpdart: ^0.6.0

  # network
  http: ^1.1.0

  # state management
  provider: ^6.0.5

  # storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # network connection checker
  connectivity_plus: ^4.0.1

  # store image on the cache
  cached_network_image: ^3.2.3

  # masonry grid view
  flutter_staggered_grid_view: ^0.6.2

  # dependency injection
  get_it: ^7.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # linter
  flutter_lints: ^2.0.0

  # dart generator
  build_runner: ^2.4.5

  # json parsing
  json_serializable: ^6.7.0
  freezed: ^2.3.5

  # unit testing
  test: ^1.24.1
  mockito: ^5.4.2

flutter:

  uses-material-design: true

  assets:
    - assets/audios/
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/lotties/
    - assets/test/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
