// Mocks generated by Mockito 5.4.2 from annotations
// in my_cat/test/features/images/data/repository/image_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:my_cat/common/data/data_source/remote_data_source/remote_data_source.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeObject_0 extends _i1.SmartFake implements Object {
  _FakeObject_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteDataSource extends _i1.Mock implements _i2.RemoteDataSource {
  @override
  _i3.Future<Object> methodGet(
    String? api, {
    int? id,
    Map<String, String>? param,
    String? baseUrl = r'api.thecatapi.com',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #methodGet,
          [api],
          {
            #id: id,
            #param: param,
            #baseUrl: baseUrl,
          },
        ),
        returnValue: _i3.Future<Object>.value(_FakeObject_0(
          this,
          Invocation.method(
            #methodGet,
            [api],
            {
              #id: id,
              #param: param,
              #baseUrl: baseUrl,
            },
          ),
        )),
        returnValueForMissingStub: _i3.Future<Object>.value(_FakeObject_0(
          this,
          Invocation.method(
            #methodGet,
            [api],
            {
              #id: id,
              #param: param,
              #baseUrl: baseUrl,
            },
          ),
        )),
      ) as _i3.Future<Object>);
}
